### ISSUE TITLE
Crash `KotlinNullPointerException` on `TileEntityBitHop.activateHopper()`

### ISSUE THREAD

**Issue by Krutoy242** [elytra/BitHop#12]
After i put bithopper to Mekanism's Crusher machine, game crashed with error:

```less
kotlin.KotlinNullPointerException
    at com.elytradev.bithop.tile.TileEntityBitHop.activateHopper(TileEntityBitHop.kt:19)
    at com.elytradev.bithop.tile.TileEntityBaseHop.TickCentral_TrueITickableUpdate(TileEntityBaseHop.kt:41)
    at com.github.terminatornl.tickcentral.api.TickHub.trueUpdate(TickHub.java:48)
    at com.github.terminatornl.laggoggles.Main.redirectUpdate(Main.java:91)
    at com.elytradev.bithop.tile.TileEntityBaseHop.update(TileEntityBaseHop.kt)
    at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38)
    at net.minecraft.world.World.updateEntities(World.java:1838)
```

[Full log `debug.log`](https://github.com/elytra/BitHop/files/9973943/debug-1.log.gz)

**Comment by Krutoy242** [comment]
Update - this only happen with BitHop and not caused by other hopper types provided by this mod.

![image](https://user-images.githubusercontent.com/936618/213421380-b84644cf-52c1-4a19-b638-ca6f5524c95c.png)
